apiVersion: v1
kind: Secret
metadata:
  name: oc-login-secret
type: Opaque
data:
  server: "{{ .Values.ocLogin.server | b64enc }}"
  username: "{{ .Values.ocLogin.username | b64enc }}"
  password: "{{ .Values.ocLogin.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
type: Opaque
data:
  pullSecret: "{{ .Values.pullSecret | b64enc }}"
