clusterName: "group3-demo"
releaseImage: "quay.io/openshift-release-dev/ocp-release:4.14.44-x86_64"
nodePoolReplicas: "2"
memory: "6Gi"
cores: "2"
etcdStorageClass: "isilon"

image:
  repository: your-docker-image
  tag: latest
  pullPolicy: IfNotPresent

hcpUrl: "https://hcp-cli-download-multicluster-engine.apps.company.com/linux/amd64/hcp.tar.gz"
ocCliUrl: "https://downloads-openshift-console.apps.company.com/amd64/linux/oc.tar"
ocLogin:
  server: "https://api.company.com:6443"
  username: ""
  password: ""

pullSecretName: pull-secret
pullSecret: ''