clusterName: "<CLUSTER_NAME>"
releaseImage: "quay.io/openshift-release-dev/ocp-release:4.14.44-x86_64"
nodePoolReplicas: "2"
memory: "6Gi"
cores: "2"
etcdStorageClass: "<STORAGE-CLASS>"

image:
  repository: <REPO>.<DOMAIN>.com/<LOC>/hosted-control-plane
  tag: latest
  pullPolicy: IfNotPresent

hcpUrl: "https://hcp-cli-download-multicluster-engine.apps.<CLUSTER>.<DOMAIN>.com/linux/amd64/hcp.tar.gz"
ocCliUrl: "https://downloads-openshift-console.apps.<CLUSTER>.<DOMAIN>.com/amd64/linux/oc.tar"
ocLogin:
  server: "https://api.<CLUSTER>.<DOMAIN>.com:6443"
  username: "<USER>"
  password: "<PASSWORD>"

pullSecretName: pull-secret
pullSecret: '<PULLSECRET>'